apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner-irsa
      initContainers:
        - name: wait-for-secret
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until [ -f /mnt/secrets/github-runner-creds ]; do echo waiting for secret; sleep 2; done"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
      containers:
        - name: github-runner
          image: "530694037299.dkr.ecr.us-east-1.amazonaws.com/github-runner-eks-image" # Replace <ECR_Image_URL> with actual URL from aws_ecr_repository.runner_ecr.repository_url
          env:
            - name: PAT
              valueFrom:
                secretKeyRef:
                  name: gh-runner-secret
                  key: access_token
            - name: GITHUB_OWNER
              value: "karthikrajkkr"
            - name: GITHUB_REPO
              value: "flaskapp-on-aws"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
            - name: RUNNER_LABELS
              value: "dev,flask-app,eks,cicd"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: "secrets-store.csi.k8s.io"
            readOnly: true
            volumeAttributes:
              secretProviderClass: "github-runner-creds"
