apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  serviceAccountName: github-runner-irsa
  containers:
  - name: example-container
    image: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secret-test-kkr"
