apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-spc
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    region: {{ .Values.secretProviderClass.region }}
    objects: |
      - objectName: "{{ .Values.secretProviderClass.awsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "{{ .Values.secretProviderClass.awsSecretKey }}"
            objectAlias: "{{ .Values.secretProviderClass.awsSecretKey }}"
  secretObjects: # This section syncs the data to a Kubernetes Secret
  - secretName: {{ .Values.secretProviderClass.kubeSecretName }}
    type: Opaque
    data:
    - key: "{{ .Values.secretProviderClass.kubeSecretKey }}"
      objectName: "{{ .Values.secretProviderClass.awsSecretKey }}"
